language: python
python:
- '3.6'
script:
- true
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment_linux.yml -n cling
- source activate cling
deploy:
  provider: pypi
  user: congzhang
  password:
    secure: WC1y6Cn4ge3AyebMymvocboPxDTMhqRQ+Q+ur13tf39/+pw3SM4qgMUPlPkGo9WS2nuPlvuYc1CB2sEOcOzdfZ1ey6QhuiaLYmfbTtHz4ok//Yuvdaw3IAqYPe0niUhzPk6wo7XV3N7FnbJXsMJQM1e8HTpUQwlxiYyH2wg/RHd+ZdVNc5XZvv5f/s0hYLcG3KoUAeP07JaTo2nPLN4BvEv7ylqywJYnVEWulTaR+OsXWAqoWciXh5Wp5SQyuU2Pba/MRa7bY3LVCTVOoSzV5ieuxVJyP+U3TYR+4gqI8W8QJrZ1bi3J3MYJzgnxyxTUzPG18yAXjkDUYl581oqjxPLWCNV1WcmLE8CkxBxjGGFofroZvhLufOC5wwnw20aGF0q8pqu5wAxCAUl+IpOIVQBCmh8ha6ds0Ei/uZxbB6BoYJsJ5aRyTVN1maNFFlOTUGeWGFjODgbGGEfYEEvOYn/h62Zg484KFYhevmruBkSwIF/9F7UmS91Tz12f5vVJDVQbKSST2/4WyvIAJ0sP1rywGhLHqv+t7OY/qY+5umbPrmYQBX3z6qyZvpbF/HAiIYrVFaCnJLF3RakKk94sj3hSgOsajonelsASB+BCd02nkmb2oCW4jQNL76jlOcD8R1Em6j9Tk1U5JvXACF5umrNIugvwQZ5BfFL8dX2Bhgg=
  on:
    distributions: sdist bdist_wheel
    repo: medlab/oum
