# packages in environment at /home/congzhang/miniconda3/envs/cling:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                    py36_0
bleach                    2.1.3                    py36_0
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py36_0
clangdev                  5.0.0                   cling_1  [cling]  QuantStack
cling                     0.5                           7  [cling]  QuantStack
cling-patches             1                             0    QuantStack
cloog                     0.18.0                        0
cmake                     3.11.0                    <pip>
cppzmq                    4.2.3                   cling_0  [cling]  QuantStack
cryptopp                  5.6.5                   cling_0  [cling]  QuantStack
dbus                      1.13.2               hc3f9b76_0
decorator                 4.3.0                    py36_0
entrypoints               0.2.3            py36h1aec115_2
expat                     2.2.5                he0dffb1_0
fftw                      3.3.4                         2    nlesc
fontconfig                2.12.6               h49f89f6_0
freetype                  2.8                  hab7d2ae_1
gcc                       4.8.2                        25    nlesc
gcc-7                     7.2.0                         2    QuantStack
glib                      2.53.6               h5d9569c_2
glibc                     2.12.2                        3    nlesc
gmp                       6.1.2                h6c8ec71_1
graphviz                  2.38.0                        4    nlesc
gsl                       1.16                          2    nlesc
gst-plugins-base          1.12.4               h33fb286_0
gstreamer                 1.12.4               hb53b477_0
html5lib                  1.0.1            py36h2f9c1c0_0
icu                       58.2                 h9c2bf20_1
ipykernel                 4.8.2                    py36_0
ipython                   6.4.0                    py36_0
ipython_genutils          0.2.0            py36hb52b0d5_0
isl                       0.17.1                        1    conda-forge
jedi                      0.12.0                   py36_1
jinja2                    2.10             py36ha16c418_0
jpeg                      9b                   h024ee3a_2
jsonschema                2.6.0            py36h006f8b5_0
jupyter_client            5.2.3                    py36_0
jupyter_core              4.4.0            py36h7c827e3_0
libcxx                    5.0.0                         0    conda-forge
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc-7                  7.2.0                         0    QuantStack
libgcc-ng                 7.2.0                hdf63c60_3
libiconv                  1.15                 h63c8f33_5
libpng                    1.6.34               hb9fc6fc_0
libsodium                 1.0.16               h1bed415_0
libstdcxx-ng              7.2.0                hdf63c60_3
libtiff                   4.0.9                he85c1e1_1
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.8                h26e45fe_1
linux-headers             2.6.32                        1    nlesc
llvmdev                   5.0.0                   cling_1  [cling]  QuantStack
markupsafe                1.0              py36hd9260cd_1
mistune                   0.8.3            py36h14c3975_1
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.1                hdf1c602_3
nbconvert                 5.3.1            py36hb41ffb7_0
nbformat                  4.4.0            py36h31c9010_0
ncurses                   6.1                  hf484d3e_0
nlohmann_json             3.1.2                         0    QuantStack
nodejs                    8.11.1               hf484d3e_0
notebook                  5.5.0                    py36_0
openssl                   1.0.2o               h20670df_0
pandoc                    1.19.2.1             hea2e7c5_1
pandocfilters             1.4.2            py36ha6701b7_1
parso                     0.2.0                    py36_0
pcre                      8.37                          5    nlesc
pexpect                   4.5.0                    py36_0
pickleshare               0.7.4            py36h63277f8_0
pip                       10.0.1                    <pip>
pip                       10.0.1                   py36_0
prompt_toolkit            1.0.15           py36h17d85b1_0
ptyprocess                0.5.2            py36h69acd42_0
pygments                  2.2.0            py36h0d3125c_0
python                    3.6.5                hc3d631a_2
python-dateutil           2.7.3                    py36_0
pyzmq                     17.0.0           py36h14c3975_0
qt                        5.9.4                h4e5bff0_0
readline                  7.0                  ha6073c6_4
root                      6.05             py3.6_gcc4.8.2    nlesc
send2trash                1.5.0                    py36_0
setuptools                39.1.0                   py36_0
simplegeneric             0.8.1                    py36_2
six                       1.11.0           py36h372c433_1
sqlite                    3.23.1               he433501_0
system                    5.8                           2
terminado                 0.8.1                    py36_1
testpath                  0.3.1            py36h8cadb63_0
tk                        8.6.7                hc745277_3
tornado                   5.0.2                    py36_0
traitlets                 4.3.2            py36h674d592_0
util-linux                2.21                          0
wcwidth                   0.1.7            py36hdf4376a_0
webencodings              0.5.1            py36h800622e_1
wheel                     0.31.1                   py36_0
widgetsnbextension        3.2.1                    py36_0
xeus                      0.12.0                  cling_0  [cling]  QuantStack
xeus-cling                0.4.3                         0    QuantStack
xproperty                 0.7.0                         0    QuantStack
xtl                       0.4.9                         0    QuantStack
xwidgets                  0.11.1                        0    QuantStack
xz                        5.2.4                h14c3975_4
zeromq                    4.2.3                h439df22_3
zlib                      1.2.11               ha838bed_2
