import pathlib
OUM_PROJECT_DIR_OBJ=pathlib.Path(__file__).parent.parent.parent
OUM_TESTWPFAPP_EXE_PATH=str(OUM_PROJECT_DIR_OBJ / 'oum' / 'uiapps' / 'wpf' / 'wpfuiapp' / 'bin' / 'Debug' / 'wpfuiapp.exe')

OUM_TESTWPFAPP_AUID_BTN_OPEN_NAME_HOLDER= 'AUID_BTN_OPEN_NAME_HOLDER'
OUM_TESTWPFAPP_ADEFAULTVALUE_BTN_OPEN_NAME_HOLDER= 'Open'

OUM_TESTWPFAPP_AUID_BTN_OPEN= 'AUID_BTN_OPEN'

OUM_TESTWPFAPP_AUID_WINDOW_MAINWINDOW= 'AUID_WINDOW_MAINWINDOW'
